on:
  pull_request:
    branches:
    - "*"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion:
          - '2.x'
        os:
          - ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        path: "fig_ws/"
    - uses: iffy/install-nim@v4
      with:
        version: ${{ matrix.nimversion }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Nimble
      run: |
        nimble install nimble
        nim -v
        nimble -v

    - name: Install Deps
      run: |
        # new atlas workspace
        nimble install -d --verbose

    - name: Test build From fig_ws/
      run: |
        nim c figuro/tests/tclick.nim

    - name: Build Tests
      run: |
        cd figuro/
        nim test
